AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.7

  Docker template for lambda

Globals:
  Function:
    Timeout: 600

Resources:
  DockerLambdaTemplate:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Policies: AmazonRDSFullAccess
      Events:
        DockerLambdaTemplate:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
    Metadata:
      Dockerfile: deploy/dockerlambdatemplate.Dockerfile
      DockerContext: .
      DockerTag: latest
